version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"          # Map host port 80 to container port 80
    volumes:
      - ./html:/usr/share/nginx/html  # Mount local directory for HTML files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Custom Nginx configuration
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
